/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiLifestyleRouteImport } from './routes/ai-lifestyle'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InvestmentEstimatorRouteImport } from './routes/investment-estimator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OwnerCommunityRouteImport } from './routes/owner-community'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as NeighbourhoodInsightsIndexRouteImport } from './routes/neighbourhood-insights.index'
import { Route as NeighbourhoodInsightsIdRouteImport } from './routes/neighbourhood-insights.$id'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLifestyleRoute = AiLifestyleRouteImport.update({
  id: '/ai-lifestyle',
  path: '/ai-lifestyle',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentEstimatorRoute = InvestmentEstimatorRouteImport.update({
  id: '/investment-estimator',
  path: '/investment-estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerCommunityRoute = OwnerCommunityRouteImport.update({
  id: '/owner-community',
  path: '/owner-community',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighbourhoodInsightsIndexRoute =
  NeighbourhoodInsightsIndexRouteImport.update({
    id: '/neighbourhood-insights/',
    path: '/neighbourhood-insights/',
    getParentRoute: () => rootRouteImport,
  } as any)
const NeighbourhoodInsightsIdRoute = NeighbourhoodInsightsIdRouteImport.update({
  id: '/neighbourhood-insights/$id',
  path: '/neighbourhood-insights/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-lifestyle': typeof AiLifestyleRoute
  '/contact': typeof ContactRoute
  '/investment-estimator': typeof InvestmentEstimatorRoute
  '/login': typeof LoginRoute
  '/owner-community': typeof OwnerCommunityRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/signin': typeof SigninRoute
  '/neighbourhood-insights/$id': typeof NeighbourhoodInsightsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/neighbourhood-insights/': typeof NeighbourhoodInsightsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-lifestyle': typeof AiLifestyleRoute
  '/contact': typeof ContactRoute
  '/investment-estimator': typeof InvestmentEstimatorRoute
  '/login': typeof LoginRoute
  '/owner-community': typeof OwnerCommunityRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/signin': typeof SigninRoute
  '/neighbourhood-insights/$id': typeof NeighbourhoodInsightsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/neighbourhood-insights': typeof NeighbourhoodInsightsIndexRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-lifestyle': typeof AiLifestyleRoute
  '/contact': typeof ContactRoute
  '/investment-estimator': typeof InvestmentEstimatorRoute
  '/login': typeof LoginRoute
  '/owner-community': typeof OwnerCommunityRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/signin': typeof SigninRoute
  '/neighbourhood-insights/$id': typeof NeighbourhoodInsightsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/neighbourhood-insights/': typeof NeighbourhoodInsightsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-lifestyle'
    | '/contact'
    | '/investment-estimator'
    | '/login'
    | '/owner-community'
    | '/privacy'
    | '/saved'
    | '/signin'
    | '/neighbourhood-insights/$id'
    | '/properties/$id'
    | '/neighbourhood-insights/'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-lifestyle'
    | '/contact'
    | '/investment-estimator'
    | '/login'
    | '/owner-community'
    | '/privacy'
    | '/saved'
    | '/signin'
    | '/neighbourhood-insights/$id'
    | '/properties/$id'
    | '/neighbourhood-insights'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-lifestyle'
    | '/contact'
    | '/investment-estimator'
    | '/login'
    | '/owner-community'
    | '/privacy'
    | '/saved'
    | '/signin'
    | '/neighbourhood-insights/$id'
    | '/properties/$id'
    | '/neighbourhood-insights/'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiLifestyleRoute: typeof AiLifestyleRoute
  ContactRoute: typeof ContactRoute
  InvestmentEstimatorRoute: typeof InvestmentEstimatorRoute
  LoginRoute: typeof LoginRoute
  OwnerCommunityRoute: typeof OwnerCommunityRoute
  PrivacyRoute: typeof PrivacyRoute
  SavedRoute: typeof SavedRoute
  SigninRoute: typeof SigninRoute
  NeighbourhoodInsightsIdRoute: typeof NeighbourhoodInsightsIdRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  NeighbourhoodInsightsIndexRoute: typeof NeighbourhoodInsightsIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-lifestyle': {
      id: '/ai-lifestyle'
      path: '/ai-lifestyle'
      fullPath: '/ai-lifestyle'
      preLoaderRoute: typeof AiLifestyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-estimator': {
      id: '/investment-estimator'
      path: '/investment-estimator'
      fullPath: '/investment-estimator'
      preLoaderRoute: typeof InvestmentEstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-community': {
      id: '/owner-community'
      path: '/owner-community'
      fullPath: '/owner-community'
      preLoaderRoute: typeof OwnerCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighbourhood-insights/': {
      id: '/neighbourhood-insights/'
      path: '/neighbourhood-insights'
      fullPath: '/neighbourhood-insights/'
      preLoaderRoute: typeof NeighbourhoodInsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighbourhood-insights/$id': {
      id: '/neighbourhood-insights/$id'
      path: '/neighbourhood-insights/$id'
      fullPath: '/neighbourhood-insights/$id'
      preLoaderRoute: typeof NeighbourhoodInsightsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiLifestyleRoute: AiLifestyleRoute,
  ContactRoute: ContactRoute,
  InvestmentEstimatorRoute: InvestmentEstimatorRoute,
  LoginRoute: LoginRoute,
  OwnerCommunityRoute: OwnerCommunityRoute,
  PrivacyRoute: PrivacyRoute,
  SavedRoute: SavedRoute,
  SigninRoute: SigninRoute,
  NeighbourhoodInsightsIdRoute: NeighbourhoodInsightsIdRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  NeighbourhoodInsightsIndexRoute: NeighbourhoodInsightsIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
